version: "3.7"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=instituicoes

  node-app:
    build: .
    command: npm start
    ports: 
        - '3333:3333'
    volumes: 
        - .:/usr/node-app